# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-23 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_favorite_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='favorite_posts',
            field=models.ManyToManyField(blank=True, related_name='favorite', to='blog.Post'),
        ),
    ]
