# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-26 16:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        ('users', '0002_auto_20160326_1542'),
    ]

    operations = [
        migrations.CreateModel(
            name='MODELNAME',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.Group')),
            ],
            bases=('auth.group',),
        ),
    ]
