# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-26 16:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_modelname'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MODELNAME',
            new_name='Group',
        ),
    ]
