# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-26 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20160326_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='favorite_posts',
            field=models.ManyToManyField(blank=True, to='blog.Post'),
        ),
    ]
