# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-25 17:44
from __future__ import unicode_literals

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20160625_2033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='facebook',
            new_name='website_url',
        ),
        migrations.RemoveField(
            model_name='user',
            name='github',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gplus',
        ),
        migrations.RemoveField(
            model_name='user',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='user',
            name='twitter',
        ),
        migrations.RemoveField(
            model_name='user',
            name='vk',
        ),
        migrations.RemoveField(
            model_name='user',
            name='website',
        ),
        migrations.AddField(
            model_name='user',
            name='facebook_url',
            field=models.URLField(blank=True, validators=[users.models.URLDomainValidator(['fb.com', 'facebook.com'])]),
        ),
        migrations.AddField(
            model_name='user',
            name='github_url',
            field=models.URLField(blank=True, validators=[users.models.URLDomainValidator(['github.com'])]),
        ),
        migrations.AddField(
            model_name='user',
            name='gplus_url',
            field=models.URLField(blank=True, validators=[users.models.URLDomainValidator(['plus.google.com'])]),
        ),
        migrations.AddField(
            model_name='user',
            name='linkedin_url',
            field=models.URLField(blank=True, validators=[users.models.URLDomainValidator(['linkedin.com'])]),
        ),
        migrations.AddField(
            model_name='user',
            name='twitter_url',
            field=models.URLField(blank=True, validators=[users.models.URLDomainValidator(['twitter.com'])]),
        ),
        migrations.AddField(
            model_name='user',
            name='vk_url',
            field=models.URLField(blank=True, validators=[users.models.URLDomainValidator(['vk.com', 'vkontakte.ru'])]),
        ),
    ]
