# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-25 17:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20160625_2144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='facebook_url',
            new_name='facebook',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='github_url',
            new_name='github',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='gplus_url',
            new_name='gplus',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='linkedin_url',
            new_name='linkedin',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='twitter_url',
            new_name='twitter',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='vk_url',
            new_name='vk',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='website_url',
            new_name='website',
        ),
    ]
