# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-29 18:55
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20160625_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='personal_info',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
    ]
