# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-08 10:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_personal_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='about',
        ),
    ]
