# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-10 12:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_user_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='activation_key',
            field=models.CharField(default='default_key', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='key_expires',
            field=models.DateField(default=datetime.datetime(2016, 7, 10, 12, 39, 51, 685654, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
