# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-10 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20160710_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activation_key',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='user',
            name='key_expires',
            field=models.DateField(blank=True),
        ),
    ]
