# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-26 10:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'get_latest_by': '-date_time', 'ordering': ['-date_time'], 'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'get_latest_by': '-date_time', 'ordering': ['-date_time'], 'verbose_name': 'Posts'},
        ),
    ]
