# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-26 10:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20160326_1021'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'get_latest_by': '-date_time', 'ordering': ['-date_time'], 'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
    ]
