# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-30 19:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flatpages', '0001_initial'),
        ('blog', '0006_auto_20160630_2259'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogFlatPage',
            fields=[
                ('flatpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='flatpages.FlatPage')),
                ('name', models.SlugField()),
            ],
            options={
                'verbose_name': 'Blog Page',
                'verbose_name_plural': 'Blog Pages',
            },
            bases=('flatpages.flatpage',),
        ),
    ]
