# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-01 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_blogflatpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogNavigation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='blogflatpage',
            name='name',
            field=models.SlugField(help_text='Name for navigation menu. Now available: "about" and "contacts"'),
        ),
        migrations.AddField(
            model_name='blognavigation',
            name='page',
            field=models.ManyToManyField(to='blog.BlogFlatPage'),
        ),
        migrations.AddField(
            model_name='blognavigation',
            name='post',
            field=models.ManyToManyField(to='blog.Post'),
        ),
    ]
