# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-26 11:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20160326_1125'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'get_latest_by': 'date_time', 'ordering': ['-date_time'], 'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
    ]
