# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-01 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20160701_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blognavigation',
            name='item',
        ),
        migrations.AddField(
            model_name='blognavigationitem',
            name='navigation',
            field=models.ManyToManyField(related_name='items', to='blog.BlogNavigation'),
        ),
    ]
