# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-26 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20160326_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='linkes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='linkes',
            field=models.IntegerField(default=0),
        ),
    ]
