# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-01 10:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20160701_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blognavigationitem',
            name='navigation',
        ),
        migrations.AddField(
            model_name='blognavigation',
            name='item',
            field=models.ManyToManyField(to='blog.BlogNavigationItem'),
        ),
    ]
