# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-01 11:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20160701_1439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blognavigation',
            name='item',
        ),
        migrations.RemoveField(
            model_name='blognavigationitem',
            name='page',
        ),
        migrations.RemoveField(
            model_name='blognavigationitem',
            name='post',
        ),
        migrations.DeleteModel(
            name='BlogNavigation',
        ),
        migrations.DeleteModel(
            name='BlogNavigationItem',
        ),
    ]
