# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-07 10:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20160701_1536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogflatpage',
            name='name',
        ),
    ]
