# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-16 18:49
from __future__ import unicode_literals

import ckeditor.fields
import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_remove_blogflatpage_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogflatpage',
            options={'verbose_name': 'Էջ', 'verbose_name_plural': 'Էջեր'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Կատեգորիա', 'verbose_name_plural': 'Կատեգորիաներ'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'get_latest_by': 'date_time', 'ordering': ['-post', 'date_time'], 'verbose_name': 'ՄԵկնաբանություն', 'verbose_name_plural': 'ՄԵկնաբանություններ'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'get_latest_by': '-date_time', 'ordering': ['-date_time', 'title'], 'verbose_name': 'Գրառում', 'verbose_name_plural': 'Գրառումներ'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Թեգեր', 'verbose_name_plural': 'Թեգեր'},
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='Նկարագրություն'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(null=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Վերնագիր'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Հեղինակ'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date_time',
            field=models.DateTimeField(auto_now=True, verbose_name='Ամսաթիվ/ժամանակ'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='likes',
            field=models.IntegerField(default=0, verbose_name='Հավանումներ'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='blog.Comment', verbose_name='Վերադաս'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Post', verbose_name='Գրառում'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(max_length=255, verbose_name='Պարունակություն'),
        ),
        migrations.AlterField(
            model_name='post',
            name='approved',
            field=models.BooleanField(default=True, verbose_name='Հաստատված է'),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Հեղինակ'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Category', verbose_name='Կատեգորիա'),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_time',
            field=models.DateTimeField(auto_now=True, verbose_name='Ամսաթիվ/ժամանակ'),
        ),
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL, verbose_name='Հավանումներ'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, to='blog.Tag', verbose_name='Թեգեր'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Պարունակություն'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Վերնագիր'),
        ),
        migrations.AlterField(
            model_name='post',
            name='views',
            field=models.IntegerField(default=0, verbose_name='Դիտումներ'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(null=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Վերնագիր'),
        ),
    ]
