# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-23 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20160716_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(verbose_name='Պարունակություն'),
        ),
    ]
