# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-10-11 15:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20160725_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ամսաթիվ/ժամանակ'),
        ),
        migrations.AlterField(
            model_name='post',
            name='excerpt',
            field=models.TextField(blank=True, null=True, verbose_name='Հատված'),
        ),
    ]
