# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-02 14:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0012_auto_20160701_1536'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogNavigation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Navigation Menu',
            },
        ),
        migrations.CreateModel(
            name='BlogNavigationItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_url', models.URLField(blank=True, null=True, unique=True)),
                ('urls_name', models.CharField(blank=True, help_text='Url name from urls.py files', max_length=255, null=True, unique=True)),
                ('icon', models.CharField(blank=True, max_length=255, null=True)),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('page', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.BlogFlatPage')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='navigation.BlogNavigationItem')),
                ('post', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Post')),
            ],
            options={
                'verbose_name': 'Menu Item',
            },
            managers=[
                ('_default_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='NavigationThrough',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='navigation.BlogNavigationItem')),
                ('navigation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='navigation.BlogNavigation')),
            ],
        ),
        migrations.AddField(
            model_name='blognavigation',
            name='nav_items',
            field=models.ManyToManyField(related_name='items', through='navigation.NavigationThrough', to='navigation.BlogNavigationItem'),
        ),
    ]
