# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-02 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blognavigationitem',
            name='manu_name',
            field=models.CharField(default='tset', max_length=255),
            preserve_default=False,
        ),
    ]
