# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-03 17:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0004_auto_20160703_1317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='navigationthrough',
            name='item',
        ),
        migrations.RemoveField(
            model_name='navigationthrough',
            name='navigation',
        ),
        migrations.AlterField(
            model_name='blognavigationitem',
            name='custom_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blognavigationitem',
            name='menu_name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='blognavigationitem',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Post', unique=True),
        ),
        migrations.AlterField(
            model_name='blognavigationitem',
            name='urls_name',
            field=models.CharField(blank=True, help_text='Url name from urls.py files', max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='NavigationThrough',
        ),
    ]
