# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-05 08:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0006_auto_20160703_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blognavigationitem',
            name='menu_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
