# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-05 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0007_auto_20160705_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='blognavigationitem',
            name='if_authenticated',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='blognavigationitem',
            name='if_not_authenticated',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='blognavigationitem',
            name='icon',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Icon'),
        ),
        migrations.AlterField(
            model_name='blognavigationitem',
            name='menu_name',
            field=models.CharField(blank=True, help_text='Name to show in menu.\n[user] variable is available', max_length=255),
        ),
    ]
