# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-05 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0008_auto_20160705_1342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blognavigationitem',
            name='if_authenticated',
        ),
        migrations.RemoveField(
            model_name='blognavigationitem',
            name='if_not_authenticated',
        ),
        migrations.AddField(
            model_name='blognavigationitem',
            name='auth',
            field=models.CharField(default="Doesn't metter", max_length=255),
            preserve_default=False,
        ),
    ]
