# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-05 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0009_auto_20160705_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blognavigationitem',
            name='auth',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
