# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-05 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0010_auto_20160705_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blognavigationitem',
            name='custom_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
