# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-07 10:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0011_auto_20160705_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blognavigationitem',
            name='menu_name',
            field=models.CharField(blank=True, help_text='Name to show in menu.\nUse [user] variable to display current user\nUse [search] variable to display search form', max_length=255),
        ),
    ]
