# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-16 18:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0012_auto_20160707_1432'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blognavigation',
            options={'verbose_name': 'Նավիգացիոն Մենյու', 'verbose_name_plural': 'Նավիգացիոն Մենյուներ'},
        ),
        migrations.AlterModelOptions(
            name='blognavigationitem',
            options={'verbose_name': 'Մենյուի օբյեկտ'},
        ),
        migrations.RemoveField(
            model_name='blognavigationitem',
            name='menu_name',
        ),
        migrations.AddField(
            model_name='blognavigationitem',
            name='name',
            field=models.CharField(blank=True, help_text='Ընտրացանկում ցուցադրվող անունը։\nՕգտագործեք [user] փոփոխականը ընթացիկ օգտագործողին ցույց տալու համար\nՕգտագործեք [search] փոփոխականը որոնման ձևը ցուցադրելու համար', max_length=255, verbose_name='Անուն'),
        ),
        migrations.AddField(
            model_name='blognavigationitem',
            name='name_for_menu',
            field=models.SlugField(default='default', help_text='Name for using in templates', verbose_name='Menu Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blognavigationitem',
            name='auth',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Իսկորոշում'),
        ),
        migrations.AlterField(
            model_name='blognavigationitem',
            name='custom_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Այլ URL'),
        ),
        migrations.AlterField(
            model_name='blognavigationitem',
            name='icon',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Պատկեր'),
        ),
        migrations.AlterField(
            model_name='blognavigationitem',
            name='page',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.BlogFlatPage', verbose_name='Էջ'),
        ),
        migrations.AlterField(
            model_name='blognavigationitem',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='navigation.BlogNavigationItem', verbose_name='Վերադաս'),
        ),
        migrations.AlterField(
            model_name='blognavigationitem',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Post', verbose_name='Գրառում'),
        ),
        migrations.AlterField(
            model_name='blognavigationitem',
            name='urls_name',
            field=models.CharField(blank=True, help_text='URL֊ի անունը urls.py ֆայլերից', max_length=255, null=True, verbose_name='URL֊ի անուն'),
        ),
    ]
