# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-16 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0013_auto_20160716_2259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blognavigationitem',
            name='name_for_menu',
        ),
        migrations.AddField(
            model_name='blognavigation',
            name='name_for_menu',
            field=models.SlugField(default='default', help_text='Name for using in templates', verbose_name='Menu Name'),
            preserve_default=False,
        ),
    ]
